export enum AuctionErrorCode {
    BID_TOO_LOW = "BID_TOO_LOW",
    AUCTION_ENDED = "AUCTION_ENDED",
    NOT_ALLOWED = "NOT_ALLOWED",
    USER_REVOKED = "USER_REVOKED",
    AUCTION_NOT_FOUND = "AUCTION_NOT_FOUND",
    RATE_LIMITED = "RATE_LIMITED",
    BID_IN_PROGRESS = "BID_IN_PROGRESS",
    DEADLINE_EXPIRED = "DEADLINE_EXPIRED",
    PAYMENT_FAILED = "PAYMENT_FAILED",
    OFFER_EXPIRED = "OFFER_EXPIRED",
    INVALID_STATUS = "INVALID_STATUS",
    NOT_FOUND = "NOT_FOUND",
    SELLER_NOT_ALLOWED = "SELLER_NOT_ALLOWED",
    NOT_PARTICIPANT = "NOT_PARTICIPANT",
    UNAUTHORIZED = "UNAUTHORIZED"
}
